import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRef, useState } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [user, setUser] = useState({ email: '', password: '' });

  async function login() {
    console.log(JSON.stringify({ user }));
  }

  return (
    <div className="bg-brand-neutral-0 h-screen">
      <Head>
        <title>Learn NestJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-stone-500">
        <h4 className="text-4xl">
          Welcome to <span className="text-blue-700">Learning Page!</span>
        </h4>
        <p className="text-2xl">
          <code className={styles.code}>You may login below</code>
        </p>

        {/* Login Form */}
        <div className="my-8">
          <input
            className="px-4 py-2 my-3 bg-blue-100 border-blue-300 border-2 rounded min-w-[280px]"
            type="email"
            value={user.email}
            onChange={(e) => setUser({ ...user, email: e.target.value })}
          />
          <input
            className="px-4 py-2 my-3 bg-blue-100 border-blue-300 border-2 rounded min-w[280px]"
            type="password"
            value={user.password}
            onChange={(e) => setUser({ ...user, password: e.target.value })}
          />
          <button onClick={login}>Login</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
